-- MySQL Script generated by MySQL Workbench
-- Fri Mar  5 12:03:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hulk_db
-- -----------------------------------------------------
-- Prueba ejercicio hulk_store

-- -----------------------------------------------------
-- Schema hulk_db
--
-- Prueba ejercicio hulk_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hulk_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `hulk_db` ;

-- -----------------------------------------------------
-- Table `hulk_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hulk_db`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hulk_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hulk_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hulk_db`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hulk_db`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `lastname` VARCHAR(30) NULL,
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_person_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `hulk_db`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hulk_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hulk_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hulk_db`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `photo` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hulk_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hulk_db`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `amount` INT NULL,
  `photo` TEXT NULL,
  `person_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hulk_db`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `hulk_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hulk_db`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hulk_db`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cart_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `hulk_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hulk_db`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
